### ISSUE TITLE
reset password dialog wont close

### ISSUE THREAD

**Issue by kiahmed** [decred/dcrstakepool#446] opened 2019-07-23 13:48 UTC
hey guys, 
having this new issue . Reset password wont just close and keep bringing the captcha challenge while there isnt any error from the browser tho, it sends reset email tho
![Capture2](https://user-images.githubusercontent.com/28849607/61717371-edb9fa00-ad2e-11e9-9b84-4404c0491a76.PNG)

**Comment by jholdstock** [comment] 2019-07-23 18:09
Hi @kiahmed, please update your code to master and confirm if you still see this issue

**Comment by JoeGruffins** [comment] 2019-07-23 22:31
@jholdstock 
I think this is how it is written. There is no confirmation after sending the email. This was also confusing for me. It just keeps looping. It does send emails, but the user isn't notified. Was there supposed to be a confirmation dialog?
There should be, but then I think we don't want email addresses to be saved in the end, for privacy reasons, so work on this will, hopefully, be useless in the end. So... If someone else wants to take this issue up that's fine, but it's not where I think we should be spending much time.

**Comment by kiahmed** [comment] 2019-07-24 00:55
well, I humbly disagree in one of the earlier implementation in my prod evn it does close and says an email been sent to that address. Its the same email that user just put to send the reset link to so not sure what privacy issue here? At least it should close it let it go or redirect to the home page or something , now its a trap

**Comment by JoeGruffins** [comment] 2019-07-24 01:08
@kiahmed 
Was the earlier implementation you are speaking of before the recent ui changes? Back when the background was all blue? I wasn't around then and I don't know what it was like.

The privacy issue has to do with the current vsp system as a whole.  Currently an email can be linked to a group of tickets.  An email can then be linked to a person.  While this may seem trivial, there is no reason for this link besides it being, probably, easier to implement. I, we?, would like voting to be completely anonymous even when using a vsp. So a change from email logins to per ticket logins is coming... just as soon as I , we?, figure out how to do it and have a plan together.

A simple redirect to the home page sounds like a quick fix tho.  Shall we do that?

**Comment by jholdstock** [comment] 2019-07-24 09:07
Guys please double check this issue actually exists in master. We did have an issue like this, but it was introduced by #375, noticed in #405 and fixed in #419. I have just tested this (for the third time) and I see no problem, the confirmation screen is displayed correctly:

![Screenshot from 2019-07-24 10-06-35](https://user-images.githubusercontent.com/6762864/61780611-c466a000-adfa-11e9-8645-1174cb776fcb.png)

**Comment by JoeGruffins** [comment] 2019-07-24 09:24
Ah, you are right. I swear I was also seeing the same behavior as @kiahmed recently.

**Comment by JoeGruffins** [comment] 2019-07-24 10:09
@jholdstock 
I think I see the cause of the confusion. A flash is only shown on success. The passwordresetError flash is being ignored.
https://github.com/decred/dcrstakepool/blob/1cc8a1be9146f989af7be8618ce7acf3fd377e2c/views/passwordreset.html#L10
If you turn off your mail server I believe you will get the same loop as us.

**Comment by JoeGruffins** [comment] 2019-07-24 10:20
Actually, thats not all of it. I will look into this later, but there's definitely times when s flash does show, and when one doesn't. I can turn off my mail server and enter a bogus email and get a success flash, but a real mail gives me the loop.

**Comment by jholdstock** [comment] 2019-07-24 12:24
You are correct. Disconnected SMTP server and entering a registered email address causes the behaviour described in the initial comment.

**Closed** 2019-07-24 20:47 UTC
